### ISSUE TITLE
MapViewer.searchUnits() fails when trying to read a unit which has no element

### ISSUE THREAD

**Issue by degenoah** [owlmaps/map-viewer#12]
This bug can be reproduced by disabling units on the map and trying to re-enable them. 

Here is the exception that is raised along with it's stacktrace.
```
main.ts:961 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at main.ts:961:37
    at NewClass.eachLayer (chunk-2ARRNFKO.js?v=c50207c9:4631:20)
    at main.ts:949:17
    at Array.forEach (<anonymous>)
    at MapViewer.searchUnits (main.ts:948:22)
    at MapViewer.updateCurrentSearchString (main.ts:544:10)
    at main.ts:531:14
    at Array.forEach (<anonymous>)
    at MapViewer.toggleUnitsLayer (main.ts:520:22)
    at main.ts:292:18
```

It seems that some layers which likely had their element deleted may still remain in `layer_units`.

**Comment by degenoah** [comment]
It seems to be an issue not with units themselves, but with the Russian units layer.

The Russian units don't seem to get re-added when you attempt to toggle the unit view on again, only Ukrainian units.
![screenshot_2024-03-11_13-24](https://github.com/owlmaps/map-viewer/assets/148393851/539302a9-268f-451d-9b70-42f3a8ac479b)

**Comment by degenoah** [comment]
This has been fixed already, closing now.
